(()=>{'use strict';
const $=id=>document.getElementById(id),db=window.TechGeekSupabase,TOKEN_KEY='tg_client_portal_token';let data=null;
const peso=v=>'₱'+Number(v||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2});
const date=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat('en-PH',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T00:00:00'))}catch(_){return v}};
const datetime=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat('en-PH',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}catch(_){return v}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(id,text,kind='err'){const n=$(id);n.textContent=text;n.className='notice show '+kind;}
function clearNotice(id){$(id).className='notice';$(id).textContent='';}
async function rpc(name,args){if(!db)throw new Error('Portal connection is not ready.');const {data,error}=await db.rpc(name,args);if(error)throw error;return data;}
async function login(){clearNotice('loginNotice');const a=$('accountNo').value.trim(),p=$('phone').value.trim();if(!a||!p)return notice('loginNotice','Enter your account number and registered mobile number.');$('loginBtn').disabled=true;$('loginBtn').textContent='Signing in…';try{const r=await rpc('client_portal_login',{p_account_no:a,p_phone:p});if(!r?.ok)return notice('loginNotice',r?.message||'Unable to sign in.');localStorage.setItem(TOKEN_KEY,r.token);await load();}catch(e){notice('loginNotice',e.message||'Unable to sign in.')}finally{$('loginBtn').disabled=false;$('loginBtn').textContent='Sign In'}}
async function load(){const token=localStorage.getItem(TOKEN_KEY);if(!token){showLogin();return}try{const r=await rpc('client_portal_get_data',{p_token:token});if(!r?.ok){localStorage.removeItem(TOKEN_KEY);showLogin();return}data=r;render();showApp();paymentReminder();}catch(e){console.error(e);showLogin();notice('loginNotice','Unable to load account data. Please try again.')}}
function showLogin(){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden')}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden')}
function render(){const c=data.client||{},b=data.current_bill||{},net=data.network||{},ppp=data.pppoe||{};$('topName').textContent=c.client_name||'Client';$('topAccount').textContent=c.account_no||'';$('hello').textContent='Hello, '+String(c.client_name||'Client').split(' ')[0]+'!';$('accountStatus').textContent='ACCOUNT: '+(c.account_status||'—');$('serviceStatus').textContent='SERVICE: '+(c.service_status||'—');const online=ppp.session_active===true||net.is_reachable===true;$('liveStatus').textContent=online?'NETWORK: ONLINE':'NETWORK: CHECKING / OFFLINE';$('plan').textContent=c.plan||'—';$('speed').textContent=c.speed||'—';$('dueDate').textContent=date(b.due_date);$('balance').textContent=peso(b.balance);$('billingPeriod').textContent=b.billing_period||'No billing record';$('billingStatus').textContent=b.billing_status||'';$('amountDue').textContent=peso(b.amount_due);$('penalty').textContent=peso(b.penalty);$('reconnect').textContent=peso(b.reconnection_fee);$('processing').textContent=peso(b.processing_fee);$('extension').textContent=peso(b.extension_fee);$('pppStatus').textContent=ppp.session_active===true?'ONLINE':ppp.secret_disabled===true?'DISABLED':'OFFLINE';$('pppStatus').className='status '+(ppp.session_active===true?'network-good':'network-bad');$('pppUpdated').textContent='Last checked: '+datetime(ppp.last_checked_at);$('netStatus').textContent=net.is_reachable===true?'REACHABLE':net.is_reachable===false?'UNREACHABLE':'NO DATA';$('netStatus').className='status '+(net.is_reachable===true?'network-good':net.is_reachable===false?'network-bad':'');$('netUpdated').textContent='Last checked: '+datetime(net.last_checked_at);$('uptime').textContent=ppp.uptime||'—';renderBills();renderPayments();renderTickets();renderNotifications();renderAccount()}
function empty(text){return '<div class="muted" style="padding:10px 0">'+esc(text)+'</div>'}
function renderBills(){const rows=data.recent_bills||[];$('billRows').innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.billing_period||x.billing_id)}</b><small>Due ${esc(date(x.due_date))}</small></div><div class="status">${esc(x.billing_status||'')}<small>${esc(peso(x.balance))} balance</small></div></div>`).join(''):empty('No billing history yet.')}
function renderPayments(){const rows=data.payments||[];$('paymentRows').innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(peso(x.amount))}</b><small>${esc(x.payment_channel||'Payment')} • ${esc(datetime(x.payment_date))}</small></div><div class="status">${esc(x.payment_status||x.confirmation_status||'')}</div></div>`).join(''):empty('No payment history yet.')}
function renderTickets(){const rows=data.tickets||[];$('ticketRows').innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.ticket_no)}</b><small>${esc(x.concern||x.issue_purpose||x.category||'Support concern')}</small></div><div class="status">${esc(x.status||'Pending')}<small>${esc(x.assigned_tech||'')}</small></div></div>`).join(''):empty('No support tickets yet.')}
function buildNotifications(){const out=[],b=data.current_bill||{},c=data.client||{};if(Number(b.balance||0)>0){if(b.due_date){const due=new Date(b.due_date+'T23:59:59'),now=new Date(data.server_time||Date.now()),days=Math.ceil((due-now)/86400000);if(days<0)out.push({t:'Payment overdue',d:`Your ${peso(b.balance)} balance is overdue. Please settle your account to avoid service interruption.`});else if(days<=5)out.push({t:'Payment reminder',d:`Your ${peso(b.balance)} bill is due ${date(b.due_date)}.`});}else out.push({t:'Outstanding balance',d:`Your current balance is ${peso(b.balance)}.`});}if(String(c.service_status||'').toLowerCase().includes('disconnect'))out.push({t:'Service status',d:'Your service is currently marked as disconnected. Check billing or contact support.'});const net=data.network||{},ppp=data.pppoe||{};if(ppp.session_active===false&&net.is_reachable===false)out.push({t:'Connection alert',d:'Your connection currently appears offline. You can create a support ticket if the issue continues.'});return out}
function renderNotifications(){const rows=buildNotifications();$('notifRows').innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.t)}</b><small>${esc(x.d)}</small></div></div>`).join(''):empty('No important alerts right now.')}
function renderAccount(){const c=data.client||{};$('accountRows').innerHTML=[['Account Number',c.account_no],['Client Name',c.client_name],['Account Status',c.account_status],['Service Status',c.service_status],['Registered Mobile',c.phone_masked],['Service Address',c.service_address],['Area / RD-BLK',c.rd_blk],['Plan',c.plan],['Speed',c.speed],['Monthly Bill',peso(c.monthly_bill)]].map(([a,b])=>`<div class="row"><div><b>${esc(a)}</b></div><div class="status">${esc(b||'—')}</div></div>`).join('')}
async function submitTicket(){clearNotice('ticketNotice');$('submitTicket').disabled=true;$('submitTicket').textContent='Submitting…';try{const r=await rpc('client_portal_create_ticket',{p_token:localStorage.getItem(TOKEN_KEY),p_category:$('ticketCategory').value,p_concern:$('ticketConcern').value,p_description:$('ticketDesc').value.trim()});if(!r?.ok)return notice('ticketNotice',r?.message||'Unable to create ticket.');notice('ticketNotice','Ticket created: '+r.ticket_no,'ok');$('ticketDesc').value='';setTimeout(async()=>{$('ticketModal').classList.add('hidden');await load()},900)}catch(e){notice('ticketNotice',e.message||'Unable to create ticket.')}finally{$('submitTicket').disabled=false;$('submitTicket').textContent='Submit Ticket'}}
async function logout(){const token=localStorage.getItem(TOKEN_KEY);try{if(token)await rpc('client_portal_logout',{p_token:token})}catch(_){}localStorage.removeItem(TOKEN_KEY);data=null;showLogin()}
async function enableNotifications(){if(!('Notification'in window))return alert('Device notifications are not supported by this browser.');const p=await Notification.requestPermission();if(p==='granted'){new Notification('TechGeekPH Client Portal',{body:'Device notifications are enabled for this portal.'});$('notifyBtn').textContent='Device Notifications Enabled'}else alert('Notification permission was not granted.')}
function paymentReminder(){if(Notification.permission!=='granted')return;const rows=buildNotifications();if(!rows.length)return;const key='tg_last_notice_'+(data.client?.account_no||'client'),stamp=new Date().toISOString().slice(0,10);if(localStorage.getItem(key)===stamp)return;new Notification(rows[0].t,{body:rows[0].d});localStorage.setItem(key,stamp)}
$('loginBtn').addEventListener('click',login);$('phone').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('accountNo').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('newTicketBtn').addEventListener('click',()=>{$('ticketModal').classList.remove('hidden');clearNotice('ticketNotice')});$('cancelTicket').addEventListener('click',()=>$('ticketModal').classList.add('hidden'));$('submitTicket').addEventListener('click',submitTicket);$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',load);$('notifyBtn').addEventListener('click',enableNotifications);document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id===b.dataset.pane))}));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(console.error));load();
})();