from pathlib import Path
import re

p=Path('tickets.html')
s=p.read_text(encoding='utf-8')

if 'referral-box' not in s:
    css='''\n.referral-box{grid-column:1/-1;border:1px solid #cfe0ee;border-radius:12px;background:#f8fbfe;padding:14px}.referral-box.hidden{display:none}.referral-box h3{margin:0;color:var(--blue);font-size:.9rem}.referral-box p{margin:5px 0 12px;color:var(--muted);font-size:.68rem;line-height:1.45}.referral-options{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.referral-opt{min-height:48px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);padding:8px 10px;text-align:left;font-weight:850;font-size:.72rem}.referral-opt small{display:block;margin-top:3px;color:var(--muted);font-size:.6rem;font-weight:700}.referral-opt.selected{border-color:var(--blue);background:#eaf4ff;color:var(--blue);box-shadow:0 0 0 2px rgba(6,79,131,.08)}.referral-opt.other{border-color:#e0c6ea}.referral-opt.none{grid-column:1/-1;text-align:center;background:#f5f7fa;color:#64748b}.referral-other-wrap{display:none;margin-top:10px}.referral-other-wrap.show{display:block}.referral-summary{margin-top:10px;padding:9px 10px;border-radius:9px;background:#eef7ff;color:#075b8e;font-size:.66rem;font-weight:800}@media(max-width:760px){.referral-options{grid-template-columns:1fr}}\n'''
    s=s.replace('</style>',css+'</style>',1)

marker='<div class="field full"><label>Concern Description / Instructions</label><textarea class="ctl" id="description" placeholder="Additional details, symptoms, landmark, instruction, materials, etc."></textarea></div>'
if marker in s and 'id="referralBox"' not in s:
    html='''<div class="field full"><label>Concern Description / Instructions</label><textarea class="ctl" id="description" placeholder="Additional details, symptoms, landmark, instruction, materials, etc."></textarea></div><section class="referral-box hidden" id="referralBox"><h3>Referral Commission</h3><p>Select all employee referrers who will share the ₱300 employee referral fee. If the referrer is not an employee, choose <b>Others</b> for the ₱200 client/other referral. Referral becomes payable only after the client completes <b>2 full monthly bills</b>; prorated bill, partial payments and fees are not counted.</p><div class="referral-options" id="referralEmployees"><button type="button" class="referral-opt none selected" data-ref-none="1">No Referral</button></div><div class="referral-other-wrap" id="referralOtherWrap"><label style="display:block;margin:0 0 6px;font-size:.7rem;font-weight:900">Other / Client Referrer Name</label><input class="ctl" id="otherReferrerName" placeholder="Full name of client or other referrer"></div><div class="referral-summary" id="referralSummary">No referral selected.</div></section>'''
    s=s.replace(marker,html,1)

old="const SB_URL='https://tcexzfztdgximrzuosqs.supabase.co',SB_KEY='sb_publishable_8H8_S7NTWvzPCLvYUe2C4g_k3Ltjfiz',CAT=window.TechGeekServiceCatalog;let db=null,tickets=[],clients=[],selectedClient=null,editing=null;"
new="const SB_URL='https://tcexzfztdgximrzuosqs.supabase.co',SB_KEY='sb_publishable_8H8_S7NTWvzPCLvYUe2C4g_k3Ltjfiz',CAT=window.TechGeekServiceCatalog;let db=null,tickets=[],clients=[],selectedClient=null,editing=null,referralEmployees=[],selectedReferralEmployees=new Set(),referralMode='NONE';"
if old in s:s=s.replace(old,new,1)

if 'function isNewInstallationForm()' not in s:
    funcs=r'''function isNewInstallationForm(){const text=n([$('#category').value,$('#concern').value,$('#serviceType').value].join(' '));return /install/.test(text)&&/(internet|isp|fiber)/.test(text)}
function referralSummary(){const box=$('#referralSummary');if(!box)return;if(referralMode==='EMPLOYEE'){const names=referralEmployees.filter(x=>selectedReferralEmployees.has(String(x.employee_id))).map(x=>x.employee_name);const each=names.length?300/names.length:0;box.textContent=names.length?'Employee Referral: ₱300 total · '+names.length+' employee(s) · approx. ₱'+each.toFixed(2)+' each':'Select at least one employee.';}else if(referralMode==='OTHER'){box.textContent='Client / Other Referral: ₱200 · payable after 2 full monthly bills.';}else box.textContent='No referral selected.'}
function renderReferralEmployees(){const wrap=$('#referralEmployees');if(!wrap)return;let html=referralEmployees.map(x=>'<button type="button" class="referral-opt '+(selectedReferralEmployees.has(String(x.employee_id))?'selected':'')+'" data-ref-id="'+esc(x.employee_id)+'">'+esc(x.employee_name)+'<small>Employee referral · share of ₱300</small></button>').join('');html+='<button type="button" class="referral-opt other '+(referralMode==='OTHER'?'selected':'')+'" data-ref-other="1">Others / Client Referrer<small>₱200 referral fee</small></button><button type="button" class="referral-opt none '+(referralMode==='NONE'?'selected':'')+'" data-ref-none="1">No Referral</button>';wrap.innerHTML=html;wrap.querySelectorAll('[data-ref-id]').forEach(b=>b.onclick=()=>{referralMode='EMPLOYEE';const id=String(b.dataset.refId);if(selectedReferralEmployees.has(id))selectedReferralEmployees.delete(id);else selectedReferralEmployees.add(id);if(!selectedReferralEmployees.size)referralMode='NONE';$('#referralOtherWrap').classList.remove('show');renderReferralEmployees();referralSummary()});const ob=wrap.querySelector('[data-ref-other]');if(ob)ob.onclick=()=>{referralMode='OTHER';selectedReferralEmployees.clear();$('#referralOtherWrap').classList.add('show');renderReferralEmployees();referralSummary();setTimeout(()=>$('#otherReferrerName').focus(),0)};const nb=wrap.querySelector('[data-ref-none]');if(nb)nb.onclick=()=>{referralMode='NONE';selectedReferralEmployees.clear();$('#otherReferrerName').value='';$('#referralOtherWrap').classList.remove('show');renderReferralEmployees();referralSummary()}}
async function loadReferralEmployees(){try{const r=await db.rpc('get_referral_employee_options');if(r.error)throw r.error;referralEmployees=r.data||[];renderReferralEmployees()}catch(e){console.warn('Referral employees unavailable',e)}}
function resetReferral(){referralMode='NONE';selectedReferralEmployees.clear();if($('#otherReferrerName'))$('#otherReferrerName').value='';if($('#referralOtherWrap'))$('#referralOtherWrap').classList.remove('show');renderReferralEmployees();referralSummary()}
function toggleReferralBox(){const box=$('#referralBox');if(!box)return;const show=isNewInstallationForm();box.classList.toggle('hidden',!show);if(!show)resetReferral()}
'''
    s=s.replace('function ticketNo(){',funcs+'\nfunction ticketNo(){',1)

pattern=r"async function createTicket\(e\)\{.*?\}\nfunction resetForm\(\)\{"
m=re.search(pattern,s,flags=re.S)
if not m: raise SystemExit('createTicket block not found')
new_create=r'''async function createTicket(e){e.preventDefault();const concern=$('#concern').value,category=$('#category').value,desc=$('#description').value.trim();const install=isNewInstallationForm();if(install&&referralMode==='EMPLOYEE'&&!selectedReferralEmployees.size)return notice('Select at least one employee referrer or choose No Referral.','err');if(install&&referralMode==='OTHER'&&!$('#otherReferrerName').value.trim())return notice('Enter the client / other referrer name.','err');const payload={ticket_no:ticketNo(),created_date:new Date().toISOString().slice(0,10),client_id:selectedClient?selectedClient.id:null,client_account_no:$('#accountNo').value.trim()||null,client_name:$('#clientName').value.trim(),contact_number:$('#contactNo').value.trim()||null,address:$('#address').value.trim()||null,category,concern,ticket_type:concern,service_type:$('#serviceType').value,issue_purpose:desc||concern,priority:$('#priority').value,assigned_tech:$('#assignedTech').value||null,status:$('#initialStatus').value,schedule_date:$('#scheduleDate').value||null,resolution:null,created_by:userName(),source_last_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(!payload.client_name||!category||!concern)return notice('Client name, category and concern are required.','err');$('#saveTicket').disabled=true;try{const r=await db.from('support_tickets').insert(payload).select().single();if(r.error)throw r.error;let referralNote='';if(install&&referralMode!=='NONE'){const rr=await db.rpc('save_installation_referral',{p_ticket_no:r.data.ticket_no,p_referral_type:referralMode,p_employee_ids:referralMode==='EMPLOYEE'?[...selectedReferralEmployees]:[],p_other_referrer_name:referralMode==='OTHER'?$('#otherReferrerName').value.trim():null});if(rr.error)referralNote=' Ticket created, but referral needs review: '+rr.error.message;else referralNote=referralMode==='EMPLOYEE'?' · Employee referral ₱300 saved.':' · Client/Other referral ₱200 saved.'}notice('Ticket '+r.data.ticket_no+' created successfully.'+referralNote,referralNote.includes('needs review')?'err':undefined);resetForm();await load();showPane('queuePane')}catch(err){notice('Unable to create ticket: '+err.message,'err')}finally{$('#saveTicket').disabled=false}}
function resetForm(){'''
s=s[:m.start()]+new_create+s[m.end():]

# Add referral reset/toggle to reset form immediately after opening brace.
s=s.replace("function resetForm(){selectedClient=null;", "function resetForm(){selectedClient=null;resetReferral();",1)
s=s.replace("$('#clientPreview').innerHTML='<div><span>Selected Client</span><b>Manual / not selected</b></div><div><span>Plan</span><b>—</b></div><div><span>RD / BLK</span><b>—</b></div><div><span>Maps</span><b>—</b></div>'}", "$('#clientPreview').innerHTML='<div><span>Selected Client</span><b>Manual / not selected</b></div><div><span>Plan</span><b>—</b></div><div><span>RD / BLK</span><b>—</b></div><div><span>Maps</span><b>—</b></div>';toggleReferralBox()}",1)

init_old="db=window.TechGeekSupabase||window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true}});setUser();setupCatalog();$('#clientSearch').addEventListener('change',e=>selectClient(e.target.value));"
init_new="db=window.TechGeekSupabase||window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true}});setUser();setupCatalog();await loadReferralEmployees();['category','concern','serviceType'].forEach(id=>$('#'+id).addEventListener('change',toggleReferralBox));$('#clientSearch').addEventListener('change',e=>selectClient(e.target.value));"
if init_old in s:s=s.replace(init_old,init_new,1)

p.write_text(s,encoding='utf-8')
print('patched tickets.html referral UI')
